version: "3.1"
services:
  server:
    image: "harryonbreadboard/sigl-server"
    ports:
      - "5600:5600"
    environment:
      PORT: 5600
      CLIENT_URL: "http://localhost:4200"
      TOKEN_SECRET: "YOUR_SECRET"
      DATABASE_URL: "postgres://postgres_user:password@database:5432/postgres_db?schema=public"
    command: >
      bash -c "
      pnpm db:reset
      && pnpm run start"