version: "3.1"
services:
  server:
    image: "stevenoumi3010/sigl-server"
    ports:
      - "5600:5600"
    env_file:
      - .env
    command: >
      bash -c "
      pnpm db:reset
      && pnpm run start"
