services:
  postgres:
    image: postgres:16.4-alpine
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres_db"
